In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pylab import *
import sklearn as sklearn
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix

red_wine = pd.read_csv('https://query.data.world/s/rrj4d2f6sj2apz4x7sozpd6epmrsiy')
white_wine = pd.read_csv('https://query.data.world/s/brho7trfnuy4iz2nxraqzsfwvgek5b')

high_quality = white_wine.loc[ white_wine['quality'] > 6 ]   #ratings 9, 8, 7 only, 1060 rows
mid_quality_initial = white_wine.loc[ white_wine['quality'] < 7 ]
mid_quality = mid_quality_initial.loc[ mid_quality_initial['quality'] > 4 ]   #ratings 5, 6 only, 3655 rows
low_quality = white_wine.loc[ white_wine['quality'] < 5 ]   #ratings 3, 4 only, 183 rows
mid_and_low_quality = white_wine.loc[ white_wine['quality'] < 7 ]   #ratings 3, 4, 5, 6 only, 3838 rows

In [2]:
#Knn classifier
from sklearn.neighbors import KNeighborsClassifier


X_initial = white_wine.drop(['quality'], axis=1)
X = X_initial[ ['alcohol', 'density', 'total sulfur dioxide', 'free sulfur dioxide', 'volatile acidity', 'fixed acidity'] ]
y = white_wine['quality']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
ks = [2,3,4,5,6,7]

for k in ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    print("For a k value = " + str(k) + " : ")
    print(confusion_matrix(y_test, y_pred, labels=[3, 4, 5, 6, 7, 8, 9]))
    print("Sum of the diagonals is: " + str(np.trace(confusion_matrix(y_test, y_pred, labels=[3, 4, 5, 6, 7, 8, 9]))) + ".")

For a k value = 2 : 
[[  1   0   2   1   1   0   0]
 [  2   9   9   4   1   0   0]
 [  2  11 205  69   3   1   0]
 [  0  17 165 212  32   6   0]
 [  2   8  40  81  59   2   0]
 [  0   1   4  18   8   4   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 490.
For a k value = 3 : 
[[  1   0   2   1   1   0   0]
 [  2   3  11   7   2   0   0]
 [  1  12 156  97  21   4   0]
 [  0  11 137 221  53  10   0]
 [  0  10  40  69  66   7   0]
 [  0   1   4  17   6   7   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 454.
For a k value = 4 : 
[[  1   0   3   0   1   0   0]
 [  1   0  14   8   2   0   0]
 [  0   7 172  87  22   3   0]
 [  0   5 128 240  49  10   0]
 [  0   3  35  87  61   6   0]
 [  0   1   2  19   7   6   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 480.
For a k value = 5 : 
[[  0   0   4   1   0   0   0]
 [  1   2  13   7   2   0   0]
 [  0   6 149 116  19   1   0]
 [  0   5 112 261  50   4   0]
 [  0   3  44  89  51   5   0]
 [  0   0   1  21

In [3]:
#knn classification taking features that seem to be strong high quality indicators
X = X_initial[ ['alcohol', 'density'] ]
y = white_wine['quality']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
ks = [2,3,4,5,6,7]

for k in ks:    
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    print("For a k value = " + str(k) + " : ")
    print(confusion_matrix(y_test, y_pred, labels=[3, 4, 5, 6, 7, 8, 9]))
    print("Sum of the diagonals is: " + str(np.trace(confusion_matrix(y_test, y_pred, labels=[3, 4, 5, 6, 7, 8, 9]))) + ".")

For a k value = 2 : 
[[  0   2   2   1   0   0   0]
 [  2   5   8   7   2   1   0]
 [  1  20 202  58   9   1   0]
 [  3  23 149 225  30   2   0]
 [  0  18  30  83  59   2   0]
 [  0   1   3  16   8   7   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 498.
For a k value = 3 : 
[[  0   0   2   3   0   0   0]
 [  2   3   9   5   5   1   0]
 [  1  15 154 103  17   1   0]
 [  1  22 106 243  55   5   0]
 [  0  15  28  66  79   4   0]
 [  0   0   1  15  11   8   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 487.
For a k value = 4 : 
[[  0   0   3   2   0   0   0]
 [  1   2  10   9   3   0   0]
 [  0   8 168  93  20   2   0]
 [  1  12 118 252  44   5   0]
 [  0   4  24  87  74   3   0]
 [  0   0   2  14  12   7   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 503.
For a k value = 5 : 
[[  0   0   3   2   0   0   0]
 [  1   1   7  11   5   0   0]
 [  0   7 172 100  12   0   0]
 [  0   5 118 264  40   5   0]
 [  0   3  24  96  67   2   0]
 [  0   0   1  19

In [4]:
#knn classification taking features that seem to be strong low quality indicators
X = X_initial[ ['free sulfur dioxide', 'volatile acidity', 'fixed acidity'] ]
y = white_wine['quality']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
ks = [2,3,4,5,6,7]

for k in ks:    
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    print("For a k value = " + str(k) + " : ")
    print(confusion_matrix(y_test, y_pred, labels=[3, 4, 5, 6, 7, 8, 9]))
    print("Sum of the diagonals is: " + str(np.trace(confusion_matrix(y_test, y_pred, labels=[3, 4, 5, 6, 7, 8, 9]))) + ".")


For a k value = 2 : 
[[  1   0   2   2   0   0   0]
 [  1   8   8   8   0   0   0]
 [  3  16 186  72  12   2   0]
 [  2  24 164 219  21   2   0]
 [  0   3  79  69  41   0   0]
 [  0   0  12  11   8   4   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 459.
For a k value = 3 : 
[[  0   0   3   1   1   0   0]
 [  1   3  11   9   1   0   0]
 [  3  14 145 102  22   5   0]
 [  1  16 122 247  44   2   0]
 [  0   1  72  65  52   2   0]
 [  0   0  13  12   5   5   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 452.
For a k value = 4 : 
[[  1   0   2   1   1   0   0]
 [  1   2  14   7   1   0   0]
 [  0   8 149 108  25   1   0]
 [  1   7 127 260  33   4   0]
 [  0   2  69  73  46   2   0]
 [  0   0  12  14   4   5   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 463.
For a k value = 5 : 
[[  1   0   3   1   0   0   0]
 [  1   3  14   7   0   0   0]
 [  0   9 137 126  18   1   0]
 [  0   8 134 257  28   5   0]
 [  0   2  70  81  38   1   0]
 [  0   0  10  16

In [5]:
#knn classification taking features that seem to be strong all around quality indicators
X = X_initial[ ['chlorides', 'residual sugar'] ]
y = white_wine['quality']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
ks = [2,3,4,5,6,7]

for k in ks:    
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    print("For a k value = " + str(k) + " : ")
    print(confusion_matrix(y_test, y_pred, labels=[3, 4, 5, 6, 7, 8, 9]))
    print("Sum of the diagonals is: " + str(np.trace(confusion_matrix(y_test, y_pred, labels=[3, 4, 5, 6, 7, 8, 9]))) + ".")


For a k value = 2 : 
[[  0   0   3   1   1   0   0]
 [  0   2  11  11   1   0   0]
 [  0  27 173  75  15   1   0]
 [  3  24 171 199  28   7   0]
 [  3  10  42  86  47   4   0]
 [  0   1   7  15   9   3   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 424.
For a k value = 3 : 
[[  0   0   2   1   2   0   0]
 [  0   2   9  12   2   0   0]
 [  2  23 126 115  22   3   0]
 [  2  20 141 218  43   8   0]
 [  3  11  37  73  62   6   0]
 [  0   1   8  12  10   4   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 412.
For a k value = 4 : 
[[  0   0   2   2   1   0   0]
 [  0   1  10  10   3   1   0]
 [  0  13 147 109  18   4   0]
 [  0  12 142 230  43   5   0]
 [  0   6  35  94  52   5   0]
 [  0   1   7  12  11   4   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 434.
For a k value = 5 : 
[[  0   0   2   2   1   0   0]
 [  0   0  10  11   4   0   0]
 [  0   6 138 130  13   4   0]
 [  1   6 134 254  33   4   0]
 [  0   0  32 105  49   6   0]
 [  0   0   6  15

The best knn classification so far is a 7 neighbor classifier on the 'alcohol' and 'density' features.

In [6]:
from sklearn import linear_model


X_initial = white_wine.drop(['quality'], axis=1)
X = X_initial[ ['alcohol', 'density', 'total sulfur dioxide', 'free sulfur dioxide', 'volatile acidity', 'fixed acidity'] ]
y = white_wine['quality']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

solvers = ['newton-cg', 'sag', 'saga', 'lbfgs' ]
for solver in solvers:
    mulnom_clf = linear_model.LogisticRegression(multi_class='multinomial', solver=solver)
    mulnom_clf.fit(X_train, y_train)
    y_pred_mulnom = mulnom_clf.predict(X_test)
    print(confusion_matrix(y_test, y_pred_mulnom, labels=[3, 4, 5, 6, 7, 8, 9]))
    print("Sum of the diagonals is: " + str(np.trace(confusion_matrix(y_test, y_pred_mulnom, labels=[3, 4, 5, 6, 7, 8, 9]))) + ".")


[[  0   0   2   2   0   1   0]
 [  0   0  14  11   0   0   0]
 [  0   0 138 151   2   0   0]
 [  1   0  91 320  20   0   0]
 [  0   0  18 138  36   0   0]
 [  0   0   2  21  12   0   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 494.


C:\Users\ramka\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:334: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


[[  0   0   2   3   0   0   0]
 [  0   0   8  16   1   0   0]
 [  0   0  88 202   1   0   0]
 [  0   0  74 355   3   0   0]
 [  0   0  17 164  11   0   0]
 [  0   0   2  29   4   0   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 454.


C:\Users\ramka\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:334: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


[[  0   0   2   3   0   0   0]
 [  0   0   7  17   1   0   0]
 [  0   0  84 205   2   0   0]
 [  0   0  76 353   3   0   0]
 [  0   0  17 169   6   0   0]
 [  0   0   2  32   1   0   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 443.
[[  1   0   2   2   0   0   0]
 [  0   0   7  18   0   0   0]
 [  0   0  88 202   1   0   0]
 [  0   0  75 356   1   0   0]
 [  0   0  18 170   4   0   0]
 [  0   0   2  33   0   0   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 449.


C:\Users\ramka\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


In [7]:
from sklearn import linear_model

high_and_low = high_quality.append(low_quality)
X_initial = high_and_low.drop(['quality'], axis=1)
X = X_initial[ ['alcohol', 'density', 'total sulfur dioxide', 'free sulfur dioxide', 'volatile acidity', 'fixed acidity'] ]
y = high_and_low['quality']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

solvers = ['newton-cg', 'sag', 'saga', 'lbfgs' ]
for solver in solvers:
    mulnom_clf = linear_model.LogisticRegression(multi_class='multinomial', solver=solver)
    mulnom_clf.fit(X_train, y_train)
    y_pred_mulnom = mulnom_clf.predict(X_test)
    print(confusion_matrix(y_test, y_pred_mulnom, labels=[3, 4, 5, 6, 7, 8, 9]))
    print("Sum of the diagonals is: " + str(np.trace(confusion_matrix(y_test, y_pred_mulnom, labels=[3, 4, 5, 6, 7, 8, 9]))) + ".")


[[  0   1   0   0   2   0   0]
 [  0  16   0   0  11   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   3   0   0 176   0   0]
 [  0   0   0   0  39   0   0]
 [  0   0   0   0   1   0   0]]
Sum of the diagonals is: 192.
[[  0   0   0   0   3   0   0]
 [  0   5   0   0  22   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   2   0   0 177   0   0]
 [  0   0   0   0  39   0   0]
 [  0   0   0   0   1   0   0]]
Sum of the diagonals is: 182.


C:\Users\ramka\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:334: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
C:\Users\ramka\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:334: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


[[  0   0   0   0   3   0   0]
 [  0   5   0   0  22   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   2   0   0 177   0   0]
 [  0   0   0   0  39   0   0]
 [  0   0   0   0   1   0   0]]
Sum of the diagonals is: 182.
[[  0   1   0   0   2   0   0]
 [  0   9   0   0  18   0   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   2   0   0 177   0   0]
 [  0   0   0   0  39   0   0]
 [  0   0   0   0   1   0   0]]
Sum of the diagonals is: 186.


C:\Users\ramka\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


In [12]:
from sklearn.ensemble import RandomForestClassifier


X_initial = white_wine.drop(['quality'], axis=1)
X = X_initial[ ['alcohol', 'density', 'total sulfur dioxide', 'free sulfur dioxide', 'volatile acidity', 'fixed acidity'] ]
y = white_wine['quality']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

estimatators = [2, 3,  4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 20, 30, 40, 50, 60, 70, 80, 90, 100 ]
for estimator in estimatators:
    ran_fores_clf = RandomForestClassifier(n_estimators=estimator)
    ran_fores_clf.fit(X_train, y_train)
    y_pred_ran_fores = ran_fores_clf.predict(X_test)
    print("For n_estimators = " + str(estimator) + ".")
    print(confusion_matrix(y_test, y_pred_ran_fores, labels=[3, 4, 5, 6, 7, 8, 9]))
    print("Sum of the diagonals is: " + str(np.trace(confusion_matrix(y_test, y_pred_ran_fores, labels=[3, 4, 5, 6, 7, 8, 9]))) + ".")
    print("---------------------------------------------------------------------------------------------------------")

For n_estimators = 2.
[[  0   1   3   1   0   0   0]
 [  3   9  10   3   0   0   0]
 [  2  20 203  62   4   0   0]
 [  0  20 133 246  33   0   0]
 [  0   5  32  81  71   3   0]
 [  0   2   4  12   5  12   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 541.
---------------------------------------------------------------------------------------------------------
For n_estimators = 3.
[[  0   0   4   1   0   0   0]
 [  0   7  12   6   0   0   0]
 [  2  20 189  73   7   0   0]
 [  1   9 104 266  48   4   0]
 [  0   8  23  61  97   3   0]
 [  0   2   2  11   5  15   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 574.
---------------------------------------------------------------------------------------------------------
For n_estimators = 4.
[[  0   0   2   3   0   0   0]
 [  0   6  13   6   0   0   0]
 [  1  17 198  68   6   1   0]
 [  0   7 105 286  30   4   0]
 [  0   2  18  67  99   5   1]
 [  0   1   1   9   8  16   0]
 [  0   0   0   0   0   0   0]]
Sum of t

In [9]:
X_initial = white_wine.drop(['quality'], axis=1)
X = X_initial[ ['alcohol', 'density', 'total sulfur dioxide', 'free sulfur dioxide', 'volatile acidity', 'fixed acidity'] ]
y = white_wine['quality']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

estimatators = [10, 20,  30, 40, 50, 60, 70, 80, 90, 100 ]
for estimator in estimatators:
    grad_boost_clf = sklearn.ensemble.GradientBoostingClassifier(n_estimators=estimator)
    grad_boost_clf.fit(X_train, y_train)
    y_pred_grad_boost = grad_boost_clf.predict(X_test)
    print("For n_estimators = " + str(estimator) + ".")
    print(confusion_matrix(y_test, y_pred_grad_boost, labels=[3, 4, 5, 6, 7, 8, 9]))
    print("Sum of the diagonals is: " + str(np.trace(confusion_matrix(y_test, y_pred_grad_boost, labels=[3, 4, 5, 6, 7, 8, 9]))) + ".")
    print("---------------------------------------------------------------------------------------------------------")


For n_estimators = 10.
[[  0   0   0   5   0   0   0]
 [  0   3  10  12   0   0   0]
 [  0   2 144 144   1   0   0]
 [  0   0  91 322  18   0   1]
 [  0   0   6 144  35   5   2]
 [  0   0   0  26   8   1   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 505.
---------------------------------------------------------------------------------------------------------
For n_estimators = 20.
[[  0   0   0   5   0   0   0]
 [  0   3  14   8   0   0   0]
 [  0   2 151 135   2   1   0]
 [  0   2  92 318  19   0   1]
 [  0   0   7 132  47   4   2]
 [  0   0   1  21  12   1   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 520.
---------------------------------------------------------------------------------------------------------
For n_estimators = 30.
[[  0   0   0   5   0   0   0]
 [  0   3  14   8   0   0   0]
 [  0   3 155 127   5   1   0]
 [  0   1  94 316  20   0   1]
 [  0   0   7 128  50   5   2]
 [  0   0   1  19  12   3   0]
 [  0   0   0   0   0   0   0]]
Sum o

Random forrest has perfromed the best out of all the classifiers. I will continue to use random forrest and tweak it further.