In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pylab import *

red_wine = pd.read_csv('https://query.data.world/s/rrj4d2f6sj2apz4x7sozpd6epmrsiy')
white_wine = pd.read_csv('https://query.data.world/s/brho7trfnuy4iz2nxraqzsfwvgek5b')

high_quality = white_wine.loc[ white_wine['quality'] > 6 ]   #ratings 9, 8, 7 only, 1060 rows
mid_quality_initial = white_wine.loc[ white_wine['quality'] < 7 ]
mid_quality = mid_quality_initial.loc[ mid_quality_initial['quality'] > 4 ]   #ratings 5, 6 only, 3655 rows
low_quality = white_wine.loc[ white_wine['quality'] < 5 ]   #ratings 3, 4 only, 183 rows
mid_and_low_quality = white_wine.loc[ white_wine['quality'] < 7 ]   #ratings 3, 4, 5, 6 only, 3838 rows

In [20]:
#Knn classifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix

X_initial = white_wine.drop(['quality'], axis=1)
X = X_initial[ ['alcohol', 'density', 'total sulfur dioxide', 'free sulfur dioxide', 'volatile acidity', 'fixed acidity'] ]
y = white_wine['quality']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
ks = [2,3,4,5,6,7]

for k in ks:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    print("For a k value = " + str(k) + " : ")
    print(confusion_matrix(y_test, y_pred, labels=[3, 4, 5, 6, 7, 8, 9]))
    print("Sum of the diagonals is: " + str(np.trace(confusion_matrix(y_test, y_pred, labels=[3, 4, 5, 6, 7, 8, 9]))) + ".")

For a k value = 2 : 
[[  1   0   2   1   1   0   0]
 [  2   9   9   4   1   0   0]
 [  2  11 205  69   3   1   0]
 [  0  17 165 212  32   6   0]
 [  2   8  40  81  59   2   0]
 [  0   1   4  18   8   4   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 490.
For a k value = 3 : 
[[  1   0   2   1   1   0   0]
 [  2   3  11   7   2   0   0]
 [  1  12 156  97  21   4   0]
 [  0  11 137 221  53  10   0]
 [  0  10  40  69  66   7   0]
 [  0   1   4  17   6   7   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 454.
For a k value = 4 : 
[[  1   0   3   0   1   0   0]
 [  1   0  14   8   2   0   0]
 [  0   7 172  87  22   3   0]
 [  0   5 128 240  49  10   0]
 [  0   3  35  87  61   6   0]
 [  0   1   2  19   7   6   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 480.
For a k value = 5 : 
[[  0   0   4   1   0   0   0]
 [  1   2  13   7   2   0   0]
 [  0   6 149 116  19   1   0]
 [  0   5 112 261  50   4   0]
 [  0   3  44  89  51   5   0]
 [  0   0   1  21

In [25]:
#knn classification taking features that seem to be strong high quality indicators
X = X_initial[ ['alcohol', 'density'] ]
y = white_wine['quality']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
ks = [2,3,4,5,6,7]

for k in ks:    
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    print("For a k value = " + str(k) + " : ")
    print(confusion_matrix(y_test, y_pred, labels=[3, 4, 5, 6, 7, 8, 9]))
    print("Sum of the diagonals is: " + str(np.trace(confusion_matrix(y_test, y_pred, labels=[3, 4, 5, 6, 7, 8, 9]))) + ".")

For a k value = 2 : 
[[  0   2   2   1   0   0   0]
 [  2   5   8   7   2   1   0]
 [  1  20 202  58   9   1   0]
 [  3  23 149 225  30   2   0]
 [  0  18  30  83  59   2   0]
 [  0   1   3  16   8   7   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 498.
For a k value = 3 : 
[[  0   0   2   3   0   0   0]
 [  2   3   9   5   5   1   0]
 [  1  15 154 103  17   1   0]
 [  1  22 106 243  55   5   0]
 [  0  15  28  66  79   4   0]
 [  0   0   1  15  11   8   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 487.
For a k value = 4 : 
[[  0   0   3   2   0   0   0]
 [  1   2  10   9   3   0   0]
 [  0   8 168  93  20   2   0]
 [  1  12 118 252  44   5   0]
 [  0   4  24  87  74   3   0]
 [  0   0   2  14  12   7   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 503.
For a k value = 5 : 
[[  0   0   3   2   0   0   0]
 [  1   1   7  11   5   0   0]
 [  0   7 172 100  12   0   0]
 [  0   5 118 264  40   5   0]
 [  0   3  24  96  67   2   0]
 [  0   0   1  19

In [19]:
#knn classification taking features that seem to be strong low quality indicators
X = X_initial[ ['free sulfur dioxide', 'volatile acidity', 'fixed acidity'] ]
y = white_wine['quality']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
ks = [2,3,4,5,6,7]

for k in ks:    
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    print("For a k value = " + str(k) + " : ")
    print(confusion_matrix(y_test, y_pred, labels=[3, 4, 5, 6, 7, 8, 9]))
    print("Sum of the diagonals is: " + str(np.trace(confusion_matrix(y_test, y_pred, labels=[3, 4, 5, 6, 7, 8, 9]))) + ".")


For a k value = 2 : 
[[  1   0   2   2   0   0   0]
 [  1   8   8   8   0   0   0]
 [  3  16 186  72  12   2   0]
 [  2  24 164 219  21   2   0]
 [  0   3  79  69  41   0   0]
 [  0   0  12  11   8   4   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 459.
For a k value = 3 : 
[[  0   0   3   1   1   0   0]
 [  1   3  11   9   1   0   0]
 [  3  14 145 102  22   5   0]
 [  1  16 122 247  44   2   0]
 [  0   1  72  65  52   2   0]
 [  0   0  13  12   5   5   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 452.
For a k value = 4 : 
[[  1   0   2   1   1   0   0]
 [  1   2  14   7   1   0   0]
 [  0   8 149 108  25   1   0]
 [  1   7 127 260  33   4   0]
 [  0   2  69  73  46   2   0]
 [  0   0  12  14   4   5   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 463.
For a k value = 5 : 
[[  1   0   3   1   0   0   0]
 [  1   3  14   7   0   0   0]
 [  0   9 137 126  18   1   0]
 [  0   8 134 257  28   5   0]
 [  0   2  70  81  38   1   0]
 [  0   0  10  16

In [21]:
#knn classification taking features that seem to be strong all around quality indicators
X = X_initial[ ['chlorides', 'residual sugar'] ]
y = white_wine['quality']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
ks = [2,3,4,5,6,7]

for k in ks:    
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    print("For a k value = " + str(k) + " : ")
    print(confusion_matrix(y_test, y_pred, labels=[3, 4, 5, 6, 7, 8, 9]))
    print("Sum of the diagonals is: " + str(np.trace(confusion_matrix(y_test, y_pred, labels=[3, 4, 5, 6, 7, 8, 9]))) + ".")


For a k value = 2 : 
[[  0   0   3   1   1   0   0]
 [  0   2  11  11   1   0   0]
 [  0  27 173  75  15   1   0]
 [  3  24 171 199  28   7   0]
 [  3  10  42  86  47   4   0]
 [  0   1   7  15   9   3   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 424.
For a k value = 3 : 
[[  0   0   2   1   2   0   0]
 [  0   2   9  12   2   0   0]
 [  2  23 126 115  22   3   0]
 [  2  20 141 218  43   8   0]
 [  3  11  37  73  62   6   0]
 [  0   1   8  12  10   4   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 412.
For a k value = 4 : 
[[  0   0   2   2   1   0   0]
 [  0   1  10  10   3   1   0]
 [  0  13 147 109  18   4   0]
 [  0  12 142 230  43   5   0]
 [  0   6  35  94  52   5   0]
 [  0   1   7  12  11   4   0]
 [  0   0   0   0   0   0   0]]
Sum of the diagonals is: 434.
For a k value = 5 : 
[[  0   0   2   2   1   0   0]
 [  0   0  10  11   4   0   0]
 [  0   6 138 130  13   4   0]
 [  1   6 134 254  33   4   0]
 [  0   0  32 105  49   6   0]
 [  0   0   6  15

The best knn classification so far is a 7 neighbor classifier on the 'alcohol' and 'density' features.

In [23]:
from sklearn.ensemble import RandomForestClassifier



chlorides  residual sugar
4656      0.048           10.80
3659      0.036            2.70
907       0.036            2.10
4352      0.054            1.60
3271      0.044            5.70
4632      0.034            8.20
2244      0.043           11.60
1924      0.032            1.60
3801      0.033            1.10
2634      0.044           14.35
2827      0.034            1.20
79        0.060            5.40
350       0.044            2.10
1370      0.052            1.90
4480      0.120           22.60
3783      0.050            8.30
2890      0.035            5.15
3193      0.038            1.00
1281      0.028            1.80
4388      0.036            7.10
653       0.053           12.30
2290      0.047            1.40
4101      0.057            9.50
1921      0.062            9.30
598       0.036           11.40
2067      0.051            4.40
2794      0.053           10.10
3826      0.034            6.80
841       0.044           13.40
2643      0.047            5.20
...         ...             ...
1808      0.065           12.40
1055      0.049            2.20
309       0.037            4.80
2370      0.039            6.00
3796      0.056           13.90
3655      0.038            5.70
527       0.034            1.80
4114      0.046            1.50
1894      0.056            6.50
2124      0.035            4.90
3598      0.033            1.40
378       0.049            2.60
495       0.025            7.00
2092      0.043            2.70
184       0.043           11.90
205       0.042           11.60
1056      0.060            1.20
410       0.038           18.95
3776      0.040            7.70
3050      0.039            1.70
3240      0.036            1.00
4089      0.098            4.60
1438      0.050            7.10
305       0.057            6.80
3347      0.055            6.70
3207      0.045            1.20
1539      0.028            5.00
964       0.034           12.50
168       0.055            8.95
3661      0.049            1.20

[980 rows x 2 columns]